config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
    get 'about',to:'pages#about'
    resources :articles
    get 'signup', to:'users#new'
    resources :users, except:[:new]

    get 'login', to:'sessions#new'
    post 'login', to:'sessions#create'
    delete 'logout', to:'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/article.rb
class Article <ActiveRecord::Base
belongs_to :user

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum:10, maximum: 200}
  validates :user_id, presence: true

end

app/models/concerns/user.rb
class User <ApplicationRecord
  has_many :articles,  dependent: :destroy
  before_save {self.email =  email.downcase}


  validates :username,presence: true,
            uniqueness:{case_sensitive: false},
            length: {minimum: 3, maximum: 50}

VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email,presence: true,
            uniqueness:{case_sensitive: false},
            length: {minimum: 3, maximum: 50},
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/models/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? #this helps the listed methods to show in views all through

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] ="You must be logged in"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController<ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except:[:index,:show]
  before_action :require_same_user, only: [:edit, :update,:destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit

  end


  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user=current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update

    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end


  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path(@article)

  end


  def show

  end



  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can edit only ur own articles"
        redirect_to root_path
      end
    end



end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
def home
  redirect_to articles_path if logged_in?
end
def about

end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

  def new

  end
  def create
    user = User.find_by(email: params[:session][:email.downcase])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id    #it is used to check session id and stor in cookies
      flash[:success] = "U have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger]="Given details do not match.Please check ur details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "U have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
  before_action :set_user, only: [:edit,:update,:show, :destroy]
  before_action :require_same_user, only: [:edit,:update, :destroy]
  before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to AlphaBlog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end
  def destroy
    @user.destroy
    flash[:danger] = "User and all Articles created by user are deleted"
    redirect_to users_path
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was successfully updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show

  end

  def index
    @users = User.all
  end

    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
    def set_user
      @user = User.find(params[:id])
    end
    def require_same_user
      if current_user != @user and !current_user.admin?
      flash[:danger] = "u can edit only ur profile details"
      redirect_to root_path
      end
    end
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only Admin can perform this action"
        redirect_to root_path
      end
    end
end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% object.each do |article| %>
  <tr>
    <td> <%= link_to article.title,article_path(article)%> </td>
    <td> <%= article.description %> </td>
    <td><% if logged_in? && (current_user == article.user || current_user.admin?) %> </td>  
      <td><%= link_to "Edit",edit_article_path(article),class: "btn btn-primary"%></td>
      <td><%= link_to "Delete",article_path(article), method: :delete, data: {confirm: "Are u sure "},class: "btn btn-primary" %></td>
    <td><% end %></td>
    <td>Created by: <%= article.user.username if article.user %></td>
    <td>Created : <%= time_ago_in_words(article.created_at) %> ago</td>
    <td>updated : <%= time_ago_in_words(article.updated_at) %> ago</td>
  </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<%if @article.errors.any?  %>
<h3>The following errors prvented from creating an article</h3>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li> <%=msg %> </li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |j|%>
  <p>
    <%= j.label :title %><br>
      <%= j.text_field :title %>
  </p>
  <p>
    <%= j.label :description %><br>
    <%= j.text_area :description %>
  </p>

  <p>
    <%= j.submit %>
  </p>

<% end %>

<p> <%= link_to "back to articles listing",articles_path%></p>

app/views/articles/edit.html.erb
<h2>Edit existing article</h2>


<%= render 'form'%>

app/views/articles/index.html.erb
<h2>List of articles</h2>

<%= render 'article',object: @articles %>

app/views/articles/new.html.erb
<h1>Create New Articles</h1>



<%= render 'form' %>

app/views/articles/show.html.erb
<h1> showing the article </h1>

<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>
 <% if @article.user %>
  <li>Created By</li>
  <p><%= link_to @article.user.username, user_path(@article.user)%></p>
  <p><%= pluralize(@article.user.articles.count, "article")%></p>
  <% end %>
<p><% if logged_in? && (current_user == @article.user || current_user.admin?) %></p>
<p><%= link_to "Edit this Article",edit_article_path(@article),class: "btn btn-primary" %></p>
<p><%= link_to "Delete",article_path(@article), method: :delete, data: {confirm: "Are u sure "},class: "btn btn-primary" %></p>
<p><% end %></p>
<p> <%= link_to "View All Articles",articles_path ,class: "btn btn-primary"%></p>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      <p>Posted by: Jithendra Prasad</p>
      <p>Contact information: <a href="mikal.jitu@gmail.com">
        mikal.jitu@gmail.com</a>.</p>
    </small>
    <nav>
      <ul>
        <li><%= link_to "about",about_path%></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <ul>
    <li> <%=msg%> </li>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id= "AP"href="#">Alpha Blog</a> -->
      <!-- this is replaced by below ruby code -->
      <%= link_to "Alpha Blog",root_path, class: "navbar-brand", id: "AP"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Article",articles_path, id: "list"%> </li>

        <li><%= link_to "Users",users_path%></li>
        <li><% if logged_in? %></li>
          <li class="dropdown">
            <a  href="#" class="dropdown-toggle" id= "create" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="#">Action</a></li> -->
              <li><%= link_to "New Article",new_article_path%></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <<li><% end %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><% if logged_in? %></li>
          <li><%= link_to "logout",logout_path, method: :delete%> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your Profile",edit_user_path(current_user)%></li>
              <li><%= link_to "View Profile ",user_path(current_user)%></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "login",login_path%> </li>
          <li><%= link_to "sign_up",signup_path%> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages'%>

    <div class="container ">
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>
<p>this will redirect you to home page:<%=link_to 'Home',root_path %></p>

app/views/pages/home.html.erb
<!-- <h1>This is home page of AlphaBlog</h1> -->
<div class="jumbotron">
  <h1>Alpha Blog</h1>
  <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p> -->
  <%= link_to "SignUp", signup_path, class:"btn btn-primary btn-lg btn-xlarge"  %>
</div>

app/views/users/_userform.html.erb
<%if @user.errors.any?  %>
<h3>The following errors prvented from creating an article</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li> <%=msg %> </li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |j|%>
  <p>
    <%= j.label :username %><br>
      <%= j.text_field :username %>
  </p>
  <p>
    <%= j.label :email %><br>
    <%= j.email_field :email %>
  </p>

  <p>
    <%= j.label :password %><br>
    <%= j.password_field :password %>
  </p>

  <p>
    <%= j.submit(@user.new_record? ? "Sign Up" :"Update", class: "btn btn-primary") %>

  </p>

<% end %>

<p> <%= link_to "back to articles listing",articles_path%></p>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>
<%= render 'userform'%>

app/views/users/index.html.erb
<h1>List of users</h1>


<% @users.each do |user| %>
<%= link_to user.username, user_path(user)%>
<%= pluralize(user.articles.count, "article") if user.articles%>
<% if logged_in? and current_user.admin? %>
<li> <%= link_to "Delete this User",user_path(user), method: :delete,
                      data: {confirm: "Are u sure you want to delete user and articles? "},class: "btn btn-primary" %> </li>
<% end %>

<% end %>

app/views/users/new.html.erb
<h1> SIGN UP FOR ALPHA BLOG</h1>
<%= render 'userform'%>

app/views/users/show.html.erb
<h1> Welcome to <%= @user.username%>'s Page </h1>

<p>username: <%= @user.username %></p>
<p>email: <%= @user.email %></p>
<%= render 'articles/article',object: @user.articles %>